"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Nav from "@/Component/Nav";
import { Provider } from "react-redux";
import store from "@/Store/store";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let queryClient = new QueryClient();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Nav></Nav>
          {children}
        </Provider>
      </body>
    </html>
  );
}
